### ISSUE TITLE
[Technical Blog] - Launching Apache DevLake (Incubating) on an AWS instance

### ISSUE THREAD

**Issue by shubham-cmyk** [merico-dev/jde-program#1]
Key pointers of blog : 
1. Setting up an SSH connection to the ec2-instance using PUTTY 
2. Setting up Docker and Docker-Compose 
3. Changing the IP in .env file to Connect Config-UI if not able to connect. 
4. Setting up the Inbound rules of AWS to connect the Grafana and Config-UI end points. 
Expected time : 24th July

**Comment by ghost** [comment]
Awesome! 

The title of the blog can be changed to **"Setting up DevLake on AWS via Docker-Compose"**

@shubham-cmyk Also update the description with ETC (estimated time of completion) so we can track the blogs and plan the content calendar for featuring your blog

**Comment by shubham-cmyk** [comment]
Thanks, for looking it out the title seems to be okay since docker-compose has to be downloaded on every platform it's a requirement to run DevLake.

**Comment by shubham-cmyk** [comment]
Reference #12 
Completed!
