### ISSUE TITLE
[Technical Blog] Colleting Data-Metrices from a multi year repository using trigger and multiple tokens.

### ISSUE THREAD

**Issue by Pranshu-Raj** [merico-dev/jde-program#10]
Topics Blog will cover:-
1. How to use advance JSON triggers.
2. Blueprint of "how to create pipelines" 

(some more topics can be added)

ETC: 26th July

**Comment by ghost** [comment]
@Pranshu-Raj Pranshu, this is awesome! We can schedule the posting  after reviewing from the DevLake team. Let me know if we can help with anything.

**Comment by ghost** [comment]
@Pranshu-Raj which repository are you planning to use for this activity?

**Comment by Pranshu-Raj** [comment]
Helm , grafana, Prometheus they are big repos and i am open for any other repo ideas if u want to suggest some.

**Comment by ghost** [comment]
Shubham tried Minikube, so maybe you can discuss with him or ask in slack.

**Comment by Pranshu-Raj** [comment]
yes, i discussed about the repos i should analyse for the same.
