### ISSUE TITLE
[Thought Piece] - FAQ section  :  Clubbing all the Issues Faced during Installation and Setting up a Pipleline

### ISSUE THREAD

**Issue by Pranshu-Raj** [merico-dev/jde-program#11]
This will provide solution for common issues faced during installation and setting up the pipeline. This is kind of on going approach which will keep evolving as every new updates have the chance for breaking some of the code and creating new bugs and issues. 

**This will be more concerned towards the user based issues instead of technical issues.**

ETC: This is not a one day blog, it will keep on evolving.

**Comment by ghost** [comment]
We can work on the FAQs section in DevLake official docs, we will gather all the questions. Thanks for taking up the initiative. Let's discuss this on Tuesday if that works for all. Meanwhile, do you have a list of FAQs in your mind?

**Comment by Pranshu-Raj** [comment]
Yes, currently I have 2-3 issues in my mind. But I think we need more issues faced by other members to create a FAQ section.

**Comment by ghost** [comment]
You can use this thread to pile up the questions before we forget. But the priority for the upcoming week would be to push blog posts and feature on different social handles.
