### ISSUE TITLE
[Technical Blog] Apache DevLake (Incubating) Codebase Walk Through

### ISSUE THREAD

**Issue by sbdtu5498** [merico-dev/jde-program#3]
In this walk-through, I would be covering the following pieces of stuff.
- What is Apache DevLake?
- Apache DevLake Architecture Overview.
- Directory Navigations and References.
- Joining Apache DevLake Community.

**Comment by ghost** [comment]
This is great! Please update the ETC (estimated time of completion) for the blog as we have to schedule in our content calendar. And definitely we can feature your blog accordingly.

Follow this template:
```
[Type of Blog] + Title //name of the issue

* Quick pointers that will be covered //points

ETC //estimated time of completion
```

**Comment by sbdtu5498** [comment]
@JoshuaPoddoku, should we close this issue? The blog has been completed and is ready to be published. It has also been reviewed by Zikuan. He has suggested some changes in the draft, you can take a look in your free time. So I think we should close this one.

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/1vYsp0ZMYVR-5PR8pw9DhwY2aZdH6yeB8HKdI4P_L6PI/edit#gid=0

Update the blog link here so we can share across the team.
