### ISSUE TITLE
[Technical Blog] DevLake - Visualize out-of-the-box engineering metrics using Grafana with data pipelines

### ISSUE THREAD

**Issue by basit9958** [merico-dev/jde-program#5]
- Deep dive data-driven engineering 
- metrics 
- logs
- metrics and log tooling

**Comment by ghost** [comment]
This is great @basit9958 ! Please update the ETC (estimated time of completion) for the blog as we have to schedule it in our content calendar. We can definitely feature your blog accordingly.

Follow this template:
```
[Type of Blog] + Title //name of the issue

* Quick pointers that will be covered //points

ETC //estimated time of completion
```
