### ISSUE TITLE
[Technical Blog & Documentation] - Devlake Helm Installation 

### ISSUE THREAD

**Issue by basit9958** [merico-dev/jde-program#6]
### This Will cover all the possible environments.

- docker
- k3s
- cri-o

**Comment by ghost** [comment]
@basit9958  Please update the ETC (estimated time of completion) for the blog as we have to schedule it in our content calendar. We can definitely feature your blog accordingly.

Follow this template:
```
[Type of Blog] + Title //name of the issue

* Quick pointers that will be covered //points

ETC //estimated time of completion
```
